# Change these first
owner: nbbrd # Your GitHub organization or username, where this repository lives
repo: sdmx-upptime # The name of this repository

sites:
  - name: ABS
    url: https://api.data.abs.gov.au/dataflow/all/all/latest
  - name: BBK
    url: https://api.statistiken.bundesbank.de/rest/metadata/dataflow/BBK
  - name: BIS
    url: https://stats.bis.org/api/v1/dataflow/all/all/latest
  - name: CAMSTAT
    url: https://nsiws-stable-camstat-live.officialstatistics.org/rest/dataflow/all/all/latest
  - name: ECB
    url: https://data-api.ecb.europa.eu/service/dataflow/all/all/latest
  - name: EC_DG_COMP
    url: https://webgate.ec.europa.eu/comp/redisstat/api/dissemination/sdmx/2.1/dataflow/all/all/latest
  - name: EC_DG_EMPL
    url: https://webgate.ec.europa.eu/empl/redisstat/api/dissemination/sdmx/2.1/dataflow/all/all/latest
  - name: EC_DG_GROW
    url: https://webgate.ec.europa.eu/grow/redisstat/api/dissemination/sdmx/2.1/dataflow/all/all/latest
  - name: ESCAP
    url: https://api-dataexplorer.unescap.org/rest/dataflow/all/all/latest
  - name: ESTAT
    url: https://ec.europa.eu/eurostat/api/dissemination/sdmx/2.1/dataflow/all/all/latest
  - name: ESTAT_COMEXT
    url: https://ec.europa.eu/eurostat/api/comext/dissemination/sdmx/2.1/dataflow/all/all/latest
  - name: ILO
    url: https://sdmx.ilo.org/rest/dataflow/all/all/latest
  - name: IMF
    url: http://dataservices.imf.org/REST/SDMX_XML.svc/Dataflow
  - name: IMF_SDMX_CENTRAL
    url: https://sdmxcentral.imf.org/ws/public/sdmxapi/rest/dataflow/all/all/latest
  - name: INEGI
    url: https://sdmx.snieg.mx/ServiceV6/rest/dataflow/all/all/latest/
  - name: INSEE
    url: https://bdm.insee.fr/series/sdmx/dataflow/all/all/latest
  - name: ISTAT
    url: https://esploradati.istat.it/SDMXWS/rest/dataflow/all/all/latest
  - name: NB
    url: https://data.norges-bank.no/api/dataflow/all/all/latest
  - name: NBB
    url: https://stat.nbb.be/restsdmx/sdmx.ashx/GetDataStructure/ALL
  - name: OECD
    url: https://sdmx.oecd.org/public/rest/dataflow/all/all/latest
  - name: SE
    url: http://andmebaas.stat.ee/restsdmx/sdmx.ashx/GetDataStructure/ALL
  - name: SGR
    url: https://registry.sdmx.org/ws/rest/dataflow/all/all/latest
  - name: SIMEL
    url: https://disseminatesimel.mtps.gob.sv/rest/dataflow/all/all/latest
  - name: SPC
    url: https://stats-nsi-stable.pacificdata.org/rest/dataflow/all/all/latest
  - name: STATCAN
    url: https://www150.statcan.gc.ca/t1/wds/rest/getAllCubesListLite
  - name: STATEC
    url: https://lustat.statec.lu/rest/dataflow/all/all/latest
  - name: TNSO
    url: https://ns1-oshub.nso.go.th/rest/dataflow/all/all/latest
  - name: UIS
    url: http://data.uis.unesco.org/RestSDMX/sdmx.ashx/GetDataStructure/ALL
  - name: UKDS
    url: https://stats2.digitalresources.jisc.ac.uk/restsdmx/sdmx.ashx/GetDataStructure/ALL
  - name: UNDATA
    url: https://data.un.org/WS/rest/dataflow/all/all/latest
  - name: UNICEF
    url: https://sdmx.data.unicef.org/ws/public/sdmxapi/rest/dataflow/all/all/latest
  - name: WB
    url: https://api.worldbank.org/v2/sdmx/rest/dataflow/all/all/latest/
  - name: WITS
    url: http://wits.worldbank.org/API/V1/SDMX/V21/rest/dataflow/all/all/latest/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /sdmx-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: SDMX Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
